name: core24
# version: "24"
adopt-info: bootstrap
summary: Runtime environment based on Ubuntu 24.04
description: |
  The base snap based on the Ubuntu 24.04 release.
confinement: strict
type: base
# This one is to trick snapcraft to not use legacy code
build-base: devel
grade: devel
assumes: [snapd2.55.5]

parts:
  base:
    plugin: nil
    source: keyrings
    build-packages:
      - wget
    build-environment:
      # When 24.04 is finally released:
      #- RELEASE: "24.04"
      #- BASE: ubuntu-base-${RELEASE}-base-${CRAFT_TARGET_ARCH}.tar.gz
      #- DIR_URL: https://cdimage.ubuntu.com/ubuntu-base/releases/${RELEASE}/release
      - BASE: noble-base-${CRAFT_TARGET_ARCH}.tar.gz
      - DIR_URL: https://cdimage.ubuntu.com/ubuntu-base/daily/current
      - URL: ${DIR_URL}/${BASE}
      - SHA256: ${DIR_URL}/SHA256SUMS
      - SIG: ${SHA256}.gpg
    override-pull: |
      craftctl default
      wget "${SHA256}" "${SIG}" "${URL}"
      gpg --no-default-keyring \
          --keyring ./cd-image-keying.gpg \
          --verify SHA256SUMS.gpg SHA256SUMS
      awk -v "file=${BASE}" '$2=="*"file' SHA256SUMS | sha256sum -c
    override-build: |
      mkdir -p "${CRAFT_PART_INSTALL}/base"
      tar -x --xattrs-include=* -f "${BASE}" -C "${CRAFT_PART_INSTALL}/base"
    override-stage: |
      rm -rf "${CRAFT_STAGE}/base"
      craftctl default
    override-prime: |
      # Do nothing
  splash-theme:
    plugin: dump
    source: https://github.com/snapcore/plymouth-theme-ubuntu-core.git
    source-type: git
    organize:
      ubuntu-core: usr/share/plymouth/themes/ubuntu-core
  netplan:
    after:
      - bootstrap
    plugin: nil
    stage-packages:
      - libnetplan0
      - libpython3-stdlib
      - libpython3.11-minimal
      - libpython3.11-stdlib
      - netplan.io
      - python3.11-minimal
      - python3-minimal
      - python3
      - python3-dbus
      - python3-netifaces
      - python3-yaml
    stage:
      - usr/bin/pdb3*
      - usr/bin/py*
      - usr/lib/python3*
      - usr/libexec
      - usr/sbin/netplan
      - usr/share/bash-completion
      - usr/share/dbus-1
      - usr/share/netplan
      - usr/share/python3
  cloud-init:
    plugin: dump
    source: cloud-init
    source-type: local
  bootstrap:
    after:
      - base
    plugin: make
    source: .
    build-packages:
      - shellcheck
      - distro-info
    override-pull: |
      craftctl set version="$(/bin/date +%Y%m%d)"
      craftctl default
    override-build: |
      craftctl default
      # create empty var/lib/console-conf
      mkdir -p ${CRAFT_PART_INSTALL}/var/lib/console-conf
    override-prime: |
      craftctl default
      # ensure build-in tests are run
      # cd ${CRAFT_PART_SRC} && make test TESTDIR=${CRAFT_PRIME}
    stage:
      - -etc/deluser.conf
      - -etc/adduser.conf
      - -usr/bin/cloud-init*
      - -usr/bin/cloud-id
      - -usr/bin/console-conf
      - -usr/bin/pdb3*
      - -usr/bin/perl*
      - -usr/bin/py*
      - -usr/lib/arm-linux-gnueabihf
      - -usr/lib/i386-linux-gnu
      - -usr/lib/cloud-init
      - -usr/lib/initramfs-tools
      - -usr/lib/ld-linux-armhf.so.*
      - -usr/lib/ld-linux.so.*
      - -usr/lib/*/perl
      - -usr/lib/*/perl-base
      - -usr/lib/*/python*
      - -usr/lib/python*
      - -usr/lib/systemd/system/cloud-*
      - -usr/lib/systemd/system-generators/cloud-init-generator
      - -usr/lib/udev/hwdb.d
      - -usr/lib/valgrind
      - -usr/sbin/addgroup
      - -usr/sbin/adduser
      - -usr/sbin/delgroup
      - -usr/sbin/deluser
      - -usr/sbin/netplan
      - -usr/share/adduser
      - -usr/share/applications/python*
      - -usr/share/apport/package-hooks/cloud-init.py
      - -usr/share/bash-completion/completions/cloud-init
      - -usr/share/bash-completion/completions/micropython
      - -usr/share/bash-completion/completions/perl*
      - -usr/share/bash-completion/completions/py*
      - -usr/share/bash-completion/helpers/perl*
      - -usr/share/bash-completion/helpers/python*
      - -usr/share/binfmts/python*
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/gcc-*
      - -usr/share/initramfs-tools
      - -usr/share/keyrings/ubuntu-cloudimage*
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/netplan
      - -usr/share/perl*
      - -usr/share/pixmaps/python*
      - -usr/share/python*
      - -usr/share/X11
      - -var/lib/python*
      - -var/lib/systemd/deb-systemd-helper-enabled/cloud-*
